
project_id = "fohvdgeknzgongfkssyc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[analytics]
enabled = true

[functions]
[functions.create-link-token]
verify_jwt = true
[functions.exchange-public-token]
verify_jwt = true

