// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/database.types';

const SUPABASE_URL = "https://fohvdgeknzgongfkssyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvaHZkZ2Vrbnpnb25nZmtzc3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTUxNDQsImV4cCI6MjA1NjE5MTE0NH0.09lPf8v_JhkokFOoj9kMunq7H2VMrdpQvwOhtjAywes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);