// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgaywqzpebunzhtemfix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYXl3cXpwZWJ1bnpodGVtZml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTg2NTAsImV4cCI6MjA1ODQ3NDY1MH0.uPNxcJ1TV4xH1Ui3lJoiT98IaVhNffKZF_Kbz-xH7rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);